### ISSUE TITLE
Profile images appear colour-inverted in some tasks lists

### ISSUE THREAD

**Issue by fromero98** [jbronssin/jira-black#18]
## Bug report
Profile images are appearing colour-inverted in some lists. For example, when you open a release, in the release tasks list.

Example:
![image](https://user-images.githubusercontent.com/1376131/207020939-b0ec716e-0ec6-46bc-90b7-35a679111bec.png)

It looks like it's related to this piece of code, as setting `filter: none;` in the HTML element using Chrome dev tools fixes it.

```css
html {
  filter: invert(86%) hue-rotate(180deg) brightness(105%) contrast(105%);
  background: white;
}
```
